name: voice-ai-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - portaudio
  - pip:
      - speechrecognition
      - google-generativeai
      - pyaudio
      - python-dotenv
      - pyttsx3
      - pywin32 
